### ISSUE TITLE
Extend Support to "Hercules CP Mobile" App

### ISSUE THREAD

**Issue by brylee123** [elahd/ha-cyclepay#24]
Hello! I stumbled upon this integration and this looks really great, but unfortunately, my building uses this version of the Hercules app so I was unable to authenticate. I was wondering if it is possible to extend support to the app listed below?

Hercules CP Mobile
iOS: https://apps.apple.com/us/app/hercules-cp-mobile/id1301857383
Android: https://play.google.com/store/apps/details?id=com.tti.kiosofthercules

Thank you!

**Comment by elahd** [comment]
Hey. The "CP" app is for Hercules laundry rooms that use KioSoft payment equipment. This integration is for rooms with ESD equipment. The bad news is that they're not compatible -- they're two different companies with two completely different APIs. The good news is that ESD's equipment is awful, so you have a better laundry room.

**Comment by madeddie** [comment]
I'm working on the kiosoft API flow, I'll likely create my own integration, but if there's interest I might try to integrate.
